spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tiny_task
    username: tiny_task
    password: demo123
  flyway:
    url: jdbc:postgresql://localhost:5432/tiny_task
    user: tiny_task
    password: demo123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host:     smtp.privateemail.com
    username: noreply@groundfloor.digital
    password: FmUNgrkB2zqeRP6
    port: 587
    properties:
      protocol: smtp
      test-connection: false
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/ttask
          jwk-set-uri: http://localhost:8083/auth/realms/ttask/protocol/openid-connect/certs

logging:
  level:
    com.coyoapp.tinytask: DEBUG
